name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"    # или go-version-file: go.mod
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.2        # свежая стабильная
          install-mode: go        # ВАЖНО: собрать линтер текущим Go
          args: --timeout=3m

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

